server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: ticket-service
            uri: lb://ticket-service
            predicates:
              - Path=/ticket-service/**
          - id: payment-validation-service
            uri: lb://payment-validation-service
            predicates:
              - Path=/payment-validation-service/**


